apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: demo
data:
  message: "Hello from the backend!"
  version: "v1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:latest
          args:
            - "-text=Backend API - Pod: $(POD_NAME)"
            - "-listen=:8080"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: message
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
