apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: demo
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      location /api {
        proxy_pass http://backend;
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>K9s Demo App</title></head>
    <body>
      <h1>K9s Demo Application</h1>
      <p>Frontend running successfully!</p>
      <button onclick="fetch('/api').then(r=>r.text()).then(t=>document.getElementById('result').innerText=t)">
        Test Backend
      </button>
      <pre id="result"></pre>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: config
          configMap:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
  type: NodePort
