version: '3'
services:
  mongo4:
    image: mongo:4.4
    command: --replSet rs0
    container_name: mongo4
    ports:
      - '27020:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet
      interval: 2s
      timeout: 3s
      retries: 5
  mongo5:
    image: mongo:4.4
    command: --replSet rs0
    container_name: mongo5
    ports:
      - '27021:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet
      interval: 2s
      timeout: 3s
      retries: 5
# services:
#   mongo1:
#     image: mongo:latest
#     container_name: mongo1
#     ports:
#       - 27017:27017
#     volumes:
#       - ./data/mongo1:/data
#     command: mongod --replSet rs0
# 
#   mongo2:
#     image: mongo:latest
#     container_name: mongo2
#     ports:
#       - 27018:27017
#     volumes:
#       - ./data/mongo2:/data
#     command: mongod --replSet rs0
# 
#   mongo3:
#     image: mongo:latest
#     container_name: mongo3
#     ports:
#       - 27019:27017
#     volumes:
#       - ./data/mongo3:/data
#     command: mongod --replSet rs0
# 
# networks:
#   default:
#     name: bridge
#     external: true
